### ISSUE TITLE
Should the sbol prefix be defined in the turtle?

### ISSUE THREAD

**Issue by bbartley** [SynBioDex/sbol-shacl#15]
Currently the sbol namespace is assigned to the default prefix `@prefix : <http://sbols.org/v3#> .`

As a result, error messages generated by the pyshacl validator may be generating some unqualified qnames.  For example, see:
https://github.com/SynBioDex/sbol_factory/issues/32

We should confirm this behavior and decide whether we want to explicitly define an `sbol` namespace in the turtle

**Comment by tcmitchell** [comment]
Tinkering around a bit, if we round-trip the [SBOL3 Ontology ](https://github.com/SynBioDex/sbol-owl3) with rdflib, we get the `sbol:` prefix back. That's probably a reasonable thing to put into `shacl_generator.py`.
