### ISSUE TITLE
Update VariableComponent to VariableFeature

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/sbol-shacl#4]
I have CombinatorialDerivations that are failing because the OWL file is still using 3.0.0 rather than 3.0.1 names.

> http://sbolstandard.org/testfiles/_2018_Interlab_ins/VariableFeature1: Value does not have class sbol:VariableComponent

**Comment by tcmitchell** [comment]
The [SBOLTestSuite](https://github.com/SynBioDex/SBOLTestSuite) does not contain any files that include `VariableFeature` (or `VariableComponent`), which is probably how this got missed. The current set of rules runs cleanly on all the examples in `SBOLTestSuite/SBOL3`.

```shell
$ find SBOLTestSuite/SBOL3 -name '*.nt' -exec grep -H Variable {} \; 
$
```

**Comment by tcmitchell** [comment]
@jakebeal can you please provide a test file for this issue?

**Comment by jakebeal** [comment]
The tests in: https://github.com/SynBioDex/SBOL-utilities/blob/master/test/test_excel_to_sbol.py
Here is a failing run showing this issue: https://github.com/SynBioDex/SBOL-utilities/runs/2688970467?check_suite_focus=true

**Comment by jakebeal** [comment]
And here's an SBOL file that directly has the problem, and could be pulled into the test suite: https://github.com/SynBioDex/SBOL-utilities/blob/master/test/test_files/simple_library.nt
